name: Java CI Workflow   # workflow name

on:
  push:
    branches: [ main ]   # triggers on push to main branch
  pull_request:
    branches: [ main ]   # triggers on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Run Maven build
      - name: Run Maven build
        run: mvn clean test

